---
title: Jokeyrhyme.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
safe: true
lsi: false
encoding: utf-8
exclude:
- bower.json
- Gemfile
- Gemfile.lock
- Gruntfile.js
- jokeyrhyme.github.com.iml
- node_modules
- package.json
- Rakefile
- README.md
