safe: true
lsi: false
highlighter: 'pygments'

markdown: kramdown

encoding: utf-8

exclude:
  - bower.json
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - jokeyrhyme.github.com.iml
  - node_modules
  - package.json
  - Rakefile
  - README.md
