safe: true
lsi: false
pygments: true

markdown: kramdown

exclude:
  - bower.json
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - jokeyrhyme.github.com.iml
  - node_modules
  - package.json
  - Rakefile
  - README.md
